require_relative 'config/environment'
require 'sinatra/activerecord/rake'

desc 'starts a Pry console'
task :console do
  # trying to add a reload function, but not yet working
  # def reload!(print = true)
  #   puts "Reloading..." if print
  #   # Main project directory
  #   root_dir = File.expand_path('.', __dir__)
  #   # Directories within the project that should be reloaded.
  #   reload_dirs = %w{app}
  #   # Loop through and reload eery file in all relevant project directories.
  #   reload_dirs.each do |dir|
  #     Dir.glob("#{root_dir}/#{dir}/**/*.rb").each {|f| load(f)}
  #   end
  #   # Return true when complete
  #   true
  # end
  # Comment out the line below if you don't want to see the SQL logs in your terminal
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  # Start a Pry session
  Pry.start
end
